language: python
python: 2.7
env:
  - TOX_ENV=py36-2.0.X
  - TOX_ENV=py36-1.11.X
  - TOX_ENV=py35-2.0.X
  - TOX_ENV=py35-1.11.X
  - TOX_ENV=py35-1.8.X
  - TOX_ENV=py27-1.11.X
  - TOX_ENV=py27-1.8.X
  - TOX_ENV=docs
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
